### PR TITLE
[WIP] Implement monitoring and alerting using CloudWatch logs

### PR DESCRIPTION
**Pull request by caggle**
While #18 implements monitoring via X-Ray, it does not provide a facility to alert when problems raise.

In this PR, I will explore a way to alert based on consumption of CloudWatch alerts. This will involve having a lambda monitoring and collecting CW logs, doing some processing and placing them on an SQS queue. The idea is to have MozDef consume that queue, and create (non-security based) alerting on MozDef.

Note: This does not mean the work in #18 is useless, we can both have X-Ray monitoring and this if we like.

### CODE REVIEW

**Comment by caggle** [comment]
As of https://github.com/mozilla/mozdef-event-framework/pull/19/commits/83653ef7c3c47f7e78f5292b0a579a2e7be3e111, I think this PR needs a bit of explaining. Main reference points used in this PR are:
- https://theburningmonk.com/2017/08/centralised-logging-for-aws-lambda/
- https://theburningmonk.com/2018/07/centralised-logging-for-aws-lambda-revised-2018/

Here is what's happening:
- In `serverless.yml` there are 2 more lambda functions, 1 more SQS queue, 1 more lambda permission, a couple more permissions to the IAM lambda role, and addition of `serverless-python-requirements` plugin. Everything except the plugin is basically in line with the articles above: 
- One lambda (`subscribeLogs`) monitors CloudTrail logs for events `CreateLogGroup` and `CreateLogStream`. When certain events fitting our criteria is found they are "forwarded" to the other lambda `shipLogsToSQS`, which performs basic processing and adds them to the logs queue. Based on my understanding, logs queue is meant to be consumed by MozDef (so we can write alerting based on it).
- The use of plugin is **not** necessary, however it made it easier for me to test this on a test serverless stack. The primary reason for the plugin is, in all other changed files, I am importing a custom Python module `cis_logger`, which is written by Mozilla IAM folks as a Python module (https://github.com/mozilla-iam/cis/tree/master/python-modules/cis_logger). This module claims to "unify logs out of mozilla iam change integration service and store them in a format consumable by MozDef.", which sounds like something we can/should re-use. The problem is it is not published on PyPi, however it can still be installed using `pip` or `setuptools` if downloaded. So I downloaded it under the `vendor` directory (manual step, but can be automated in a CI environment), and produced a `requirements.txt` file and added this local module as a requirement (also a manual step, but can be automated in CI). Lines 42-46 simply configure this plugin to install this module, so our code can use it.
- With the use of `cis_logger` module, our lambda functions now log in JSON format, for instance:
    ```
      {
       "asctime": "2019-11-20T01:10:58Z+0000",
       "name": "root",
       "processName": "MainProcess",
       "filename": "handler.py",
       "funcName": "lambda_handler",
       "levelname": "INFO",
       "lineno": 78,
       "module": "handler",
       "threadName": "MainThread",
       "message": "Event added to the resource queue.",
       "timestamp": "2019-11-20T01:10:58Z+0000",
       "hostname": "169.254.209.37"
      }
    ```
    and we are filtering based on the `levelname` key, i.e. any log for our lambda functions in this stack that has a level of WARNING or ERROR will be picked up by `shipLogsToSQS` function, and will be added to the `LogsQueue`.
- As mentioned above, everything under `vendor` is actually another module (not developed by me, so no review is required)

I have deployed a test stack with this PR and it works well - WARNING and ERROR messages are added to an SQS queue. You can see the `test-dev` stack and `test-test-dev-CWLogs` queue in our AWS Console for an example.

TODO items remaining before this PR is ready for review:
- [ ] Decide if we would like to use `serverless-python-requirements` plugin to manage 3rd party/custom Python module imports, _OR_ we keep installing Python modules/dependencies using `pip` via`buildspec.yml` before deployment. Plugin is the easier option in my mind (moving forward as well, as we may implement custom modules to break down functionality), and it appears to be still supported/kept up to date. However a clear con of this approach is that our serverless stack with the use of plugin becomes considerably bigger (approx. 25 mb in size in this case), since the plugin packages all modules and their requirements in the `requirements.txt` file together with our lambda function.
- [x] Write unit tests for the `log_handler.py` file.
- [ ] Make sure relevant changes are made to the CF templates to support this to ensure it's deploy-able via AWS CodePipeline.

@Phrozyn, this is not a review request yet however please let me know if this makes sense thus far. Happy to walk you through in person if you like.

**Comment by Phrozyn** [comment]
Lets talk about this a bit in person. 
I have questions :)

**Comment by caggle** [comment]
Sure. In the mean time, here are some more thoughts:

- If we want to implement this kind of pattern (monitor cloudtrail events for cloudwatch logs, and do processing on the ones which interests us) we do not _need_ to use `cis_logger` module. We could normally log and perform filtering on that, this would eliminate some complexity and the need of a custom module.
- Having said this, we cannot keep avoiding having custom modules, if we would like this framework to be truly modular and unit-testable (JSON schema validation implementation is a good reason for having modules, if we would like to be able to validate a variety of different events, not only webhook events). 3rd party modules that are available on PyPi are less of a problem since we can install them as a dependency during build time (without the need of a plugin), however eventually we will need to address how to import/incorporate custom modules into our code. Based on my research/understanding, we can take one of the 3 approaches for this:

    **1. Write or pull down custom modules and keep them as a part of the framework in another directory, and have `serverless-python-requirements` plugin to handle all 3rd party + custom module dependencies.**
    - This is the approach I took in this PR. I am not advocating for this, I just used it to demonstrate a deployable and working stack.
    - A con of this approach is that our lambda functions code size increases, due to bundling of all dependencies with the actual function code.
    - A pro of this is it's relatively easy, we just need to maintain `requirements.txt` file, and the plugin will do the rest. 

  **2. Pull down and install all 3rd party + custom modules during the CI build (via buildspec), before deploying the framework**
    - This option does not use the plugin, at all.
    - The process would be something like this: https://medium.com/@manivannan_data/import-custom-python-packages-on-aws-lambda-function-5fbac36b40f8
    - A pro is we/the person who develops/deploys has the ultimate control of dependencies
    - A con is that this would create a lambda function large in size, due to bundling all dependencies in a virtual environment (similar to above).

  **3. Install 3rd party/custom modules as lambda layers**
    - Again, no need for a plugin, it is more of a  "AWS-native" solution
    - An example of this is explained in this article: https://nordcloud.com/lambda-layers-for-python-runtime/
    - This is also the approach taken by the IAM folks in CIS project: https://github.com/mozilla-iam/cis
    - A con of this is that it looks a bit complex, but I think this can be automated during CI.
    - A pro of this is to keep the lambda functions code small and lean. This would also help in writing unit tests (i.e. we would mostly eliminate the need of mocking AWS services, can only unit-test the custom modules).

Since this is a larger issue than just "monitoring", I will create an issue about it.

**Comment by caggle** [comment]
I created an issue for the last comment above.

Also, as per discussions, we will not complete this work at this time, although the idea remains as an option.

**Pull request closed without merging**
