### PR TITLE
Attempt implementation of monitoring with X-Ray

### PR DESCRIPTION
**Pull request by caggle**

### CODE REVIEW

**Comment by caggle** [comment]
I did some reading, and found this link: https://serverless-stack.com/chapters/tracing-serverless-apps-with-x-ray.html

Looks like we actually do not need the plugin, serverless framework from version 1.44 appears to natively support X-Ray.

However, it seems, to enable X-Ray tracing on services invoked by AWS lambda, the `aws-xray-sdk` should be added. We should probably need this if we would like to monitor end-to-end (including addition to the resource queue). I will keep playing with this.

**Comment by caggle** [comment]
OK, my understanding/experience thus far:
- We don't need the `serverless-plugin-tracing` plugin.
- `aws_xray_sdk` is a 3rd party module, that needs to be installed as a dependency (in buildspec)
-  When installed and used as per this PR (in particular, the `patch_all()` function, it patches all included modules, and tracks/trace their performance. For instance, by patching the `boto3` module, we can see the performance (as well as the API calls) SSM, or to SQS queue. This is good and what we want.

Other things for consideration:
- Is there an alerting/notification method for X-Ray to alert when a performance threshold is reached, or e.g. more than 10 HTTP 500 errors occurred in the last minute. I will keep investigating.

**Comment by caggle** [comment]
I did some more reading. It looks like alerting / notifying via X-Ray is not possible, unless we start creating Cloudwatch events based on X-Ray data, which sounds complex to me.

I will investigate using CloudWatch and metric filters for this instead. Might do this in another PR.

The only remaining challenge for using X-Ray is to have the unit tests pass while it's in use. `moto` can apparently fully mock X-Ray, will investigate this option now.

**Comment by caggle** [comment]
I ended up disabling X-Ray for unit tests, as it seemed like a pain to mock it when `patch_all` is used.

**Comment by caggle** [comment]
I think this is ready for review. However it should be reviewed after #17 is reviewed and merged, as it builds on top of that.

**Comment by Phrozyn** [comment]
I had a branch made for this locally :) Looks like you discovered many of the same things I did during my journey! Thank you for doing this!

**Review by Phrozyn — APPROVED** [review]

**Pull request merged**
