### PR TITLE
shortening names so that roles/perms will be readable

### PR DESCRIPTION
**Pull request by Phrozyn**

### CODE REVIEW

**Comment by caggle** [comment]
Looks good thus far.

I also had a look at the template for venues to shorten names even further. We could use stuff like "CC" instead of codecommit, or "PPL" instead of Pipeline, but I am not sure if this would sacrifice readability (However we could increase readability with more comments in the template).

@Phrozyn let me know what you think, otherwise I am happy to approve this PR (if it's ready for approval).

**Review by arzzen — DISMISSED** [review]

**Comment by Phrozyn** [comment]
@caggle What do you think about us transitioning these sections:

```
      PolicyName:
        'Fn::Join': [ "", ["CWCommitEventPolicy", "-", !Ref 'AWS::StackName', "-", !Ref 'Environment']]
```
These will start to run together after we deploy several of these, so my thinking is have the stack name first like so:

      PolicyName:
        'Fn::Join': [ "", [ !Ref 'AWS::StackName', "-", !Ref 'Environment', "-", "CWCommitEventPolicy"]]

They'll be easier to spot in a list like that.

**Comment by Phrozyn** [comment]
Also I took your recommendation and used CC, CB, CW, and PL for the various services.

**Comment by caggle** [comment]
> @caggle What do you think about us transitioning these sections:
> 
> ```
>       PolicyName:
>         'Fn::Join': [ "", ["CWCommitEventPolicy", "-", !Ref 'AWS::StackName', "-", !Ref 'Environment']]
> ```
> 
> These will start to run together after we deploy several of these, so my thinking is have the stack name first like so:
> 
> ```
>   PolicyName:
>     'Fn::Join': [ "", [ !Ref 'AWS::StackName', "-", !Ref 'Environment', "-", "CWCommitEventPolicy"]]
> ```
> 
> They'll be easier to spot in a list like that.

I like it!

Also had a look at the changes, they look good with the short names and comments.

**Review by caggle — APPROVED** [review]

**Pull request merged**
